service: typescript-serverless-skeleton

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-2

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get